-- ============================================
-- 五险一金计算器 - Supabase 表结构
-- ============================================

-- 1. 创建城市标准表 (cities)
CREATE TABLE IF NOT EXISTS cities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city_name TEXT NOT NULL,
  year TEXT NOT NULL,
  base_min INTEGER NOT NULL CHECK (base_min > 0),
  base_max INTEGER NOT NULL CHECK (base_max > 0),
  rate NUMERIC(5, 4) NOT NULL CHECK (rate > 0),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 唯一约束：同一城市同一年只能有一条记录
CREATE UNIQUE INDEX IF NOT EXISTS cities_city_year_idx ON cities(city_name, year);

-- 2. 创建员工工资表 (salaries)
CREATE TABLE IF NOT EXISTS salaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT NOT NULL,
  employee_name TEXT NOT NULL,
  month TEXT NOT NULL CHECK (month ~ '^\d{6}$'), -- YYYYMM 格式
  salary_amount NUMERIC(12, 2) NOT NULL CHECK (salary_amount > 0),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 唯一约束：同一员工同一个月只能有一条记录
CREATE UNIQUE INDEX IF NOT EXISTS salaries_employee_month_idx ON salaries(employee_id, month);

-- 3. 创建计算结果表 (results)
CREATE TABLE IF NOT EXISTS results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT NOT NULL,
  employee_name TEXT NOT NULL,
  city_name TEXT NOT NULL,
  year TEXT NOT NULL,
  avg_salary NUMERIC(12, 2) NOT NULL,
  contribution_base NUMERIC(12, 2) NOT NULL,
  company_fee NUMERIC(12, 2) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 普通索引用于查询优化
CREATE INDEX IF NOT EXISTS results_employee_idx ON results(employee_id);
CREATE INDEX IF NOT EXISTS results_city_year_idx ON results(city_name, year);

-- ============================================
-- 启用 Row Level Security (RLS)
-- ============================================

-- 对于 MVP 阶段，先禁用 RLS 以便 API 可以正常访问
-- 生产环境建议启用 RLS 并配置适当的安全策略

ALTER TABLE cities ENABLE ROW LEVEL SECURITY;
ALTER TABLE salaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE results ENABLE ROW LEVEL SECURITY;

-- 允许所有操作（MVP 阶段，生产环境需加强安全策略）
CREATE POLICY "Enable all access for cities" ON cities
  FOR ALL USING (true)
  WITH CHECK (true);

CREATE POLICY "Enable all access for salaries" ON salaries
  FOR ALL USING (true)
  WITH CHECK (true);

CREATE POLICY "Enable all access for results" ON results
  FOR ALL USING (true)
  WITH CHECK (true);

-- ============================================
-- 测试数据（可选）
-- ============================================

-- 插入示例城市数据
INSERT INTO cities (city_name, year, base_min, base_max, rate) VALUES
  ('佛山', '2024', 2390, 20268, 0.151),
  ('广州', '2024', 2390, 20268, 0.151)
ON CONFLICT (city_name, year) DO NOTHING;

-- 插入示例工资数据
INSERT INTO salaries (employee_id, employee_name, month, salary_amount) VALUES
  ('E001', '张三', '202401', 8000),
  ('E001', '张三', '202402', 8000),
  ('E001', '张三', '202403', 8000),
  ('E001', '张三', '202404', 8500),
  ('E001', '张三', '202405', 8500),
  ('E001', '张三', '202406', 8500),
  ('E001', '张三', '202407', 8500),
  ('E001', '张三', '202408', 8500),
  ('E001', '张三', '202409', 9000),
  ('E001', '张三', '202410', 9000),
  ('E001', '张三', '202411', 9000),
  ('E001', '张三', '202412', 9000),
  ('E002', '李四', '202401', 12000),
  ('E002', '李四', '202402', 12000),
  ('E002', '李四', '202403', 12000),
  ('E002', '李四', '202404', 12500),
  ('E002', '李四', '202405', 12500),
  ('E002', '李四', '202406', 12500),
  ('E002', '李四', '202407', 12500),
  ('E002', '李四', '202408', 12500),
  ('E002', '李四', '202409', 13000),
  ('E002', '李四', '202410', 13000),
  ('E002', '李四', '202411', 13000),
  ('E002', '李四', '202412', 13000)
ON CONFLICT (employee_id, month) DO NOTHING;
