-- Supabase 数据库表创建脚本

-- 创建 cities 表
create table if not exists cities (
  id bigint generated by default as identity primary key,
  city_name text not null,
  year text not null,
  base_min integer not null,
  base_max integer not null,
  rate numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 添加唯一约束
alter table cities add constraint cities_city_name_year_key unique (city_name, year);

-- 创建 salaries 表
create table if not exists salaries (
  id bigint generated by default as identity primary key,
  employee_id text not null,
  employee_name text not null,
  month text not null,
  salary_amount integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 添加唯一约束
alter table salaries add constraint salaries_employee_id_month_key unique (employee_id, month);

-- 创建 results 表
create table if not exists results (
  id bigint generated by default as identity primary key,
  employee_id text not null,
  employee_name text not null,
  city_name text not null,
  year text not null,
  avg_salary numeric not null,
  contribution_base numeric not null,
  company_fee numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 启用 RLS（可选）
-- alter table cities enable row level security;
-- alter table salaries enable row level security;
-- alter table results enable row level security;

-- 允许公开访问（MVP 阶段）
-- create policy "Allow public access to cities" on cities for select using (true);
-- create policy "Allow public insert to cities" on cities for insert with check (true);
-- create policy "Allow public update to cities" on cities for all using (true);

-- create policy "Allow public access to salaries" on salaries for select using (true);
-- create policy "Allow public insert to salaries" on salaries for insert with check (true);
-- create policy "Allow public update to salaries" on salaries for all using (true);

-- create policy "Allow public access to results" on results for select using (true);
-- create policy "Allow public insert to results" on results for insert with check (true);
-- create policy "Allow public delete to results" on results for all using (true);
